### ISSUE TITLE
Dump game button not displayed

### ISSUE THREAD

**Issue by andrew-thox** [Spuckwaffel/UEDumper#10]
Hi, I'm on the v1.5 stable beta on the start page i get a Process ID and Base Address but the dump game button isn't displayed. I don't think it's cutoff like in one of the previous issues. I can see blank space under base address. Is it's appearance conditional? Maybe I missed something.

**Comment by Spuckwaffel** [comment]
hey there, could you share a screenshot of the issue?

**Comment by andrew-thox** [comment]
![image](https://github.com/Spuckwaffel/UEDumper/assets/678817/e716dea1-ace2-4bb5-9b9b-153f8ac99cf6)

Sure thing! Log line 4 was me mispelling the .exe name

**Comment by Spuckwaffel** [comment]
you have to press the create button before which creates the project folder

**Comment by andrew-thox** [comment]
You are right. I was missing that the project name had to be 5 chars. I should read properly next time. Thanks
