### ISSUE TITLE
Question : Always get this error

### ISSUE THREAD

**Issue by TheGeogeo** [Spuckwaffel/UEDumper#16]
Hi, I want dump Farlight SDK but i get this error all the time. (I always using CE and IDA for getting address and offset) So it's first time i tried something else.

Thx for your reply 🙏

https://imgur.com/a/3Rl01NO
https://imgur.com/a/xtuUCGH
https://imgur.com/a/0UGuTy5
https://imgur.com/a/SGse47S

**Comment by Spuckwaffel** [comment]
hey there, looking at the log you have a wrong gobject address. The addresses look very wrong and 99 million objects doesnt look right. Are you sure you got the right offset?

**Comment by TheGeogeo** [comment]
`int flag = -1; //flag of the Offset struct
std::string name = ""; //name of the Offset struct
int offset = 0; //if using flag OFFSET_ADDRESS, set the address here (dont write base +..., just write the offset)
//leave the rest empty if not using a sig
const char* sig = ""; //sig bytes in format \xAB\xCD\xEF\x00\x...
std::string mask = ""; //xxxxxxx??xxx??x? where x compares the byte and ? is a wildcard.`

`std::vector<Offset> offsets;

offsets.push_back({ OFFSET_ADDRESS | OFFSET_DH, "OFFSET_GNAMES", 0x69E81E8 });
offsets.push_back({ OFFSET_ADDRESS | OFFSET_DH, "OFFSET_GOBJECTS", 0x69ECDB0 });
offsets.push_back({ OFFSET_ADDRESS | OFFSET_DH | OFFSET_LIVE_EDITOR, "OFFSET_UWORLD", 0x78915F8 });`

You talk about that ?

**Comment by Spuckwaffel** [comment]
the offsets, yes, you have to set them to initialise the engine. Without offsets the dumper won't find anything.

**Comment by TheGeogeo** [comment]
> the offsets, yes, you have to set them to initialise the engine. Without offsets the dumper won't find anything.

Ok i understand your comment line bellow thx for your answer :)
