### ISSUE TITLE
new version Unreal 5.3 does not work

### ISSUE THREAD

**Issue by NetoScript** [Spuckwaffel/UEDumper#17]
A game called (Mini Royale) came out on Steam, I found all the necessary addresses for the SDK to be generated, UEDumper is closed after you try to dump the game

error image->[https://cdn.discordapp.com/attachments/627282020430512138/1160469002464800848/image.png?ex=6534c5fa&is=652250fa&hm=12d02d106dfde7aabd5fbc79a88d7793d832d980f2808df8a465b362dd1ed127&](url)

Game Steam->[https://store.steampowered.com/app/1657090/Mini_Royale/](url)

Adresses
GName 0x7A96B00
GObject 0x7B3E5C0
GWorld 0x7CAED18

**Comment by Spuckwaffel** [comment]
Hey there, 
Can you post the full log? Or send a link to the log?
It seems like you might have wrong settings (macros) in the UEdefinitions.h file, because your offsets seem right (maybe recheck gobjects).
You can try setting some macros from FALSE to TRUE and the other way, especially those for the Struct settings. If the error still exists, try setting a breakpoint in the package generation function, single step through it and tell me where it raises the error.

**Comment by NetoScript** [comment]
here are the logs 

0 [12:43:19 - MAIN]: Loading program...
1 [12:43:19 - MAIN]: Loaded imgui helper library...
2 [12:43:19 - MEMORY]: Initializing memory class...
3 [12:43:19 - MEMORY]: Initialized Memory class!
4 [12:43:27 - MEMORY]: Loaded Memory class!
5 [12:43:29 - DUMPPROGRESS]: Starting dump...
6 [12:43:29 - ENGINECORE]: Loading core...
7 [12:43:29 - OBJECTSMANAGER]: TUObject -> 0x000001CC83CF40C0
8 [12:43:29 - OBJECTSMANAGER]: TUObject elements: 68591
9 [12:43:29 - OBJECTSMANAGER]: TUObject -> 0x000001CC83CF40C0
10 [12:43:29 - OBJECTSMANAGER]: Allocated 802C800 bytes for FFields cache
11 [12:43:29 - OBJECTSMANAGER]: Allocated 61A800 bytes for FFieldClass cache
12 [12:43:29 - OBJECTSMANAGER]: Allocating 0x0000000000191E68 bytes of memory for GObjectPtrArray at 0x0000016DD6F90040
13 [12:43:29 - OBJECTSMANAGER]: Loaded GObjectPtrArray succesfully!
14 [12:43:29 - ENGINECORE]: Allocating 0x29DD58 bytes of memory for UBigObjectArray at 0x0000016DE2530040
15 [12:43:29 - ENGINECORE]: Could not resolve address for obect 65169!
16 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68582!
17 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68583!
18 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68584!
19 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68585!
20 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68586!
21 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68587!
22 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68588!
23 [12:43:29 - ENGINECORE]: Could not resolve address for obect 68589!
24 [12:43:29 - ENGINECORE]: Loaded UBigObjectArray succesfully!
25 [12:43:29 - ENGINECORE]: Caching FNames...
26 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 65169 in getUObjectByIndex is marked invalid!
27 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68582 in getUObjectByIndex is marked invalid!
28 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68583 in getUObjectByIndex is marked invalid!
29 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68584 in getUObjectByIndex is marked invalid!
30 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68585 in getUObjectByIndex is marked invalid!
31 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68586 in getUObjectByIndex is marked invalid!
32 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68587 in getUObjectByIndex is marked invalid!
33 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68588 in getUObjectByIndex is marked invalid!
34 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68589 in getUObjectByIndex is marked invalid!
35 [12:43:29 - ENGINECORE]: Cached all FNames!
36 [12:43:29 - ENGINECORE]: Caching all Packets...
37 [12:43:29 - ENGINECORE]: reading overriding structs....
38 [12:43:29 - ENGINECORE]: adding custom structs....
39 [12:43:29 - ENGINECORE]: adding overrigind unknown members....
40 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 65169 in getUObjectByIndex is marked invalid!
41 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68582 in getUObjectByIndex is marked invalid!
42 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68583 in getUObjectByIndex is marked invalid!
43 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68584 in getUObjectByIndex is marked invalid!
44 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68585 in getUObjectByIndex is marked invalid!
45 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68586 in getUObjectByIndex is marked invalid!
46 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68587 in getUObjectByIndex is marked invalid!
47 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68588 in getUObjectByIndex is marked invalid!
48 [12:43:29 - OBJECTSMANAGER]: WARN: Requested index 68589 in getUObjectByIndex is marked invalid!
49 [12:43:29 - ENGINECORE]: Total packages: 197
50 [12:43:29 - CORE]: Generating Class EngineSettings::UConsoleSettings
51 [12:43:29 - CORE]: member None size is 0! 
52 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
53 [12:43:29 - CORE]: Generating Class EngineSettings::UGameMapsSettings
54 [12:43:29 - CORE]: member None size is 0! 
55 [12:43:29 - CORE]: Total member count: 2 | Function count: 3
56 [12:43:29 - CORE]: Generating Class EngineSettings::UGameNetworkManagerSettings
57 [12:43:29 - CORE]: member None size is 0! 
58 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
59 [12:43:29 - CORE]: Generating Class EngineSettings::UGameSessionSettings
60 [12:43:29 - CORE]: member None size is 0! 
61 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
62 [12:43:29 - CORE]: Generating Class EngineSettings::UGeneralEngineSettings
63 [12:43:29 - CORE]: Total member count: 0 | Function count: 0
64 [12:43:29 - CORE]: Generating Class EngineSettings::UGeneralProjectSettings
65 [12:43:29 - CORE]: member None size is 0! 
66 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
67 [12:43:29 - CORE]: Generating Class EngineSettings::UHudSettings
68 [12:43:29 - CORE]: member None size is 0! 
69 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
70 [12:43:29 - CORE]: Generating Enum FETwoPlayerSplitScreenType
71 [12:43:29 - CORE]: Generating Enum FEThreePlayerSplitScreenType
72 [12:43:29 - CORE]: Generating Enum FEFourPlayerSplitScreenType
73 [12:43:29 - CORE]: Generating Enum FESubLevelStripMode
74 [12:43:29 - CORE]: Generating Struct EngineSettings::FAutoCompleteCommand
75 [12:43:29 - CORE]: member None size is 0! 
76 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
77 [12:43:29 - CORE]: Generating Struct EngineSettings::FGameModeName
78 [12:43:29 - CORE]: member None size is 0! 
79 [12:43:29 - CORE]: Total member count: 2 | Function count: 0
80 [12:43:29 - CORE]: Generating Struct EngineSettings::FTemplateMapInfoOverride
81 [12:43:29 - OBJECTSMANAGER]: ERROR! Could not find the requested Pointer 27A6C027A94027B in the cache!

**Comment by NetoScript** [comment]
It looks like only GObject has a problem, maybe it's incorrect or it could be encrypted

**Comment by Spuckwaffel** [comment]
gworld is not needed, ill check this out, this seems strange. It looks like it can't find the child members, they might have a different offset. Is the game free and does it have an ac? I can check it out once I have free time

**Comment by Spuckwaffel** [comment]
also as mentioned earlier, try to set some macros to true or false, try maybe setting USTRUCT_FAST_ISCHILDOF_IMPL to FALSE

**Comment by NetoScript** [comment]
the game is in BETA available on Steam

AntiCheat EAC
Bypass -> change the product in the anticheat json file put Dank

![image](https://github.com/Spuckwaffel/UEDumper/assets/59490830/82466575-1630-41b9-9962-65ef59258b88)

**Comment by NetoScript** [comment]
> também como mencionado anteriormente, tente definir algumas macros como verdadeiras ou falsas, tente talvez definir USTRUCT_FAST_ISCHILDOF_IMPL como FALSE


thank you very much it worked

![image](https://github.com/Spuckwaffel/UEDumper/assets/59490830/e64d4e88-a2f6-4ea0-8914-f586874221a8)

**Comment by Spuckwaffel** [comment]
verycool

**Comment by NetoScript** [comment]
> muito legal

![image](https://github.com/Spuckwaffel/UEDumper/assets/59490830/cd46092b-d77f-4cbc-b7fd-3fd2de75bb80)

**Comment by Spuckwaffel** [comment]
the uworld offset is somehow wrong, look there it points to on the heap. The address is not valid
