### ISSUE TITLE
MDK Compilation Errors

### ISSUE THREAD

**Issue by FruitBoi** [Spuckwaffel/UEDumper#27]
Hey,

I noticed when compiling an MDK for the latest version of fortnite, using the fortnite branch, there are several compilation errors in the merged_UI_UIKit.h header.

MDK/merged_UI_UIKit.h(1562,38): error : expected class name
MDK/merged_UI_UIKit.h(1662,38): error : expected class name

It appears that the classes are being defined in the wrong order, with dependencies being below dependents. 

I can upload the MDK dump in question if needed, it should be easily reproducible with the current Fortnite branch on Fortnite v27.10 though

Thank you! :)

**Comment by Spuckwaffel** [comment]
hey there, thanks for the report. Would you be able to upload the MDK/post pictures of it? Are you sure it's the MDK itself and not any code you added?

**Comment by FruitBoi** [comment]
Absolutely, here is the relevant MDK and SaveState files.
The only change I made to MDK before compilation was to move all classes into a separate namespace for organization.

[Fortnite-v27.10.zip](https://github.com/Spuckwaffel/UEDumper/files/13404351/Fortnite-v27.10.zip)
[SaveState.zip](https://github.com/Spuckwaffel/UEDumper/files/13404352/SaveState.zip)

**Comment by Spuckwaffel** [comment]
ive looked into it and it was an issue on my side. I pushed a fix:
https://github.com/Spuckwaffel/UEDumper/commit/58b25611fd67ccb4f862524ef500be494b06a9a0
apparently my loop never executed twice or more for the struct reordering, because i forgot to set a bool to true 🤡 
I tested it and it compiles now without an issue.

**Comment by Spuckwaffel** [comment]
im really surprised this issue never happened before/in testing as i really thought multiple iterations of struct reordering are necessary.

**Comment by FruitBoi** [comment]
Glad to see it was a simple fix :)
