### ISSUE TITLE
TUObject Pointer is invaild. This mean the OFFSETS_GObjects offsets is wrong. Please fix this.

### ISSUE THREAD

**Issue by qq1091192337** [Spuckwaffel/UEDumper#28]
![QQ截图20231121211428](https://github.com/Spuckwaffel/UEDumper/assets/30151531/d7d3d824-85ad-47a5-b84c-5a3e74f23b33)
I have encountered a problem with the content mentioned above.
Game name: Insurgency: Sandstorm

**Comment by Spuckwaffel** [comment]
Please read the README.md carefully before opening a issue. You have to set the offsets before dumping.
