### ISSUE TITLE
It seems unable to dump classes inherited from UBlueprintFunctionLibrary

### ISSUE THREAD

**Issue by VSEdison** [Spuckwaffel/UEDumper#34]
Game:Valorant
logs:
superstruct failed!
name: /Script/CoreUObject.Default__Class
name: /Script/CoreUObject.Default__Class
superstruct failed!
name: /Script/CoreUObject.Default__DynamicClass
name: /Script/CoreUObject.Default__DynamicClass
superstruct failed!
name: /Script/CoreUObject.Default__LinkerPlaceholderClass
name: /Script/CoreUObject.Default__LinkerPlaceholderClass
superstruct failed!
name: /Script/Engine.Default__BlueprintGeneratedClass
name: /Script/Engine.Default__BlueprintGeneratedClass
superstruct failed!
name: /Script/Engine.Default__AnimBlueprintGeneratedClass
name: /Script/Engine.Default__AnimBlueprintGeneratedClass
superstruct failed!
name: /Script/UMG.Default__WidgetBlueprintGeneratedClass
name: /Script/UMG.Default__WidgetBlueprintGeneratedClass
superstruct failed!
name: /Script/ControlRig.Default__ControlRigBlueprintGeneratedClass
name: /Script/ControlRig.Default__ControlRigBlueprintGeneratedClass

sdk result:
/// Class /Script/Engine.BlueprintFunctionLibrary
/// Size: 0x0000 (0x000030 - 0x000030)
class UBlueprintFunctionLibrary : public UObject
{ 
public:
};

/// Class /Script/ShooterGame.ContentLibrary
/// Size: 0x0000 (0x000030 - 0x000030)
class UContentLibrary : public UBlueprintFunctionLibrary
{ 
public:
};

All classes that inherit from UBlueprintFunctionLibrary get the same result
Unable to get functions in the UBlueprintFunctionLibrary class

**Comment by Spuckwaffel** [comment]
hey there, this doesnt look like an issue to me as the size of these classes is 0. Are you sure these classes should not be empty?

**Comment by VSEdison** [comment]
Yes, I'm sure it's not empty, there should be some game functions in it.
Here's what I got from the other dumper:

// Class ShooterGame.ContentLibrary
// Size: 0x30 (Inherited: 0x30)
struct UContentLibrary : UBlueprintFunctionLibrary {

	bool IsSprayLevelDisabled(struct UObject* WorldContextObject, struct USprayLevelDataAsset* SprayLevelAsset); // Function ShooterGame.ContentLibrary.IsSprayLevelDisabled // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x36f5a50
	bool IsRandomSelectionAsset(struct UAresBasePrimaryDataAsset* BaseDataAsset); // Function ShooterGame.ContentLibrary.IsRandomSelectionAsset // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x36f59c0
	......

**Comment by Spuckwaffel** [comment]
i will look into it. Thanks!

**Comment by Spuckwaffel** [comment]
hey there, just got home from vacation. Does this bug affect any variables that are supposed to be in the class or only functions?

**Comment by Spuckwaffel** [comment]
Looks like I found the root of the issue. This will be fixed in the next version. Thanks for the report!
For a temporary fix in your version go to Core.cpp@EngineCore::generateFunctions Line 398 and remove the ``|| !object->ChildProperties``
