### ISSUE TITLE
Failed to allocate memory for GObjectPtrArray

### ISSUE THREAD

**Issue by Nou4r** [Spuckwaffel/UEDumper#35]
![image](https://github.com/Spuckwaffel/UEDumper/assets/12816677/e3c29cee-13e1-43d7-8cb6-82a231728e18)
I have set the right offsets in Offsets.h and set the right Engine Version (4.27) in UEdefinitions.h

**Comment by Spuckwaffel** [comment]
hey there,
check the log for more information. Most likely your GObject pointer is wrong.

**Comment by Spuckwaffel** [comment]
could you please send the log of the dumper
