### ISSUE TITLE
I crashed after dumping torchilight.

### ISSUE THREAD

**Issue by C-Abner** [Spuckwaffel/UEDumper#36]
I crashed after dumping torchilight.

msg is :

"Sorry! You ran into a unrecoverable errorthat forces the Dumper to close.
Failed to allocate memory forUBigObjectArray!"

**Comment by Spuckwaffel** [comment]
hey there, please look at the log in the log window. I'm very sure that it's due to a faulty GObject offset.

**Comment by C-Abner** [comment]
0 [13:11:17 - MAIN]: Loading program...
1 [13:11:17 - MAIN]: Loaded imgui helper library...
2 [13:11:17 - MEMORY]: Initializing memory class...
3 [13:11:17 - MEMORY]: Initialized Memory class!
4 [13:11:22 - MEMORY]: Error getting base address!
5 [13:11:55 - MEMORY]: Loaded Memory class!
6 [13:11:57 - DUMPPROGRESS]: Starting dump...
7 [13:11:57 - ENGINECORE]: Loading core...
8 [13:11:57 - OBJECTSMANAGER]: TUObject -> 0x058B48F1F7480000
9 [13:11:57 - OBJECTSMANAGER]: TUObject elements: 2038515743
10 [13:11:57 - OBJECTSMANAGER]: TUObject -> 0x058B48F1F7480000
11 [13:11:57 - OBJECTSMANAGER]: Allocated 802C800 bytes for FFields cache
12 [13:11:57 - OBJECTSMANAGER]: Allocated 61A800 bytes for FFieldClass cache
13 [13:11:58 - OBJECTSMANAGER]: Allocating 0x00000000641EC2E8 bytes of memory for GObjectPtrArray at 0x0000028769FF3070
14 [13:11:58 - OBJECTSMANAGER]: Loaded GObjectPtrArray successfully!
15 [13:11:58 - ENGINECORE]: Allocating 0x12FC3344D8 bytes of memory for UBigObjectArray at 0x0000000000000000
16 [13:11:58 - ENGINECORE]: Failed to allocate memory for UBigObjectArray!
17 [13:11:58 - DUMPPROGRESS]: No success at copyUBigObjects!

**Comment by Spuckwaffel** [comment]
object count 2038515743? Doesn't look right to me. Looks like invalid GObjects pointer.

**Comment by C-Abner** [comment]
can you help me?

**Comment by Spuckwaffel** [comment]
how am i supposed to help you lol? You need the right offsets. You can find them by reversing the game.
