### ISSUE TITLE
dumper error crash

### ISSUE THREAD

**Issue by byxiaoxie** [Spuckwaffel/UEDumper#38]
![20240122011357](https://github.com/Spuckwaffel/UEDumper/assets/10564149/f81215c0-22dc-40ba-91da-f9141aa9e2c3)

Game: Palworld

What did it cause to crash?

In using the old version 1.6.2 it is normal dumper
Using 1.7 will get an error crash

offsets.push_back({ OFFSET_ADDRESS | OFFSET_DS, "OFFSET_GNAMES", 0x8717A00 });
offsets.push_back({ OFFSET_ADDRESS | OFFSET_DS, "OFFSET_GOBJECTS", 0x87B7100 });
offsets.push_back({ OFFSET_ADDRESS | OFFSET_DS | OFFSET_LIVE_EDITOR, "OFFSET_UWORLD", 0x8924E28 });

**Comment by Spuckwaffel** [comment]
whats the crash reason

**Comment by byxiaoxie** [comment]
> whats the crash reason
The console only shows the error cache The exact cause is unclear.

**Comment by Spuckwaffel** [comment]
please check out the visual studio output while running the process. It should throw an exception somewhere. Also, does the generation just freeze or what's happening?

**Comment by byxiaoxie** [comment]
std::string UObject::getName() const
{
    return EngineCore::FNameToString(NamePrivate);  // Error, this is nullptr。
}

**Comment by byxiaoxie** [comment]
if (!ClassPrivate) // Error, this is nullptr。
{
    return { false, PropertyType::Unknown, getName() };
}

So far I've processed all nullptrc to return None, and it works fine!

**Comment by byxiaoxie** [comment]
Maybe my OFFSET_GNAMES is incorrect?

**Comment by byxiaoxie** [comment]
Thanks for your help, I have fixed it!

**Comment by Spuckwaffel** [comment]
awesome
