### ISSUE TITLE
Buffer Issue

### ISSUE THREAD

**Issue by MrReekoFTWxD** [Spuckwaffel/UEDumper#4]
On some game im my case, Six Days in Fallujah the buffer inside 

```
void windows::PackageViewerWindow::generatePackage(std::ofstream& file, const EngineStructs::Package& package)
{
...
 for (const auto& member : struc.members)
            {
                char finalBuf[300];
                char nameBuf[200];
...
}
```
was to small for some objects to dump full sdk simple fix i just increased them both to 0x500 just figured id let you know beside that issue i only ran into on a few games everything else works great

**Comment by Spuckwaffel** [comment]
Thank you for the report! I fixed this issue in the commit above. Keep in mind that the current branch is the development branch and will be in the master branch in the next UEDumper version (which might take a bit).
