### ISSUE TITLE
No Success at caching FNames

### ISSUE THREAD

**Issue by Chaos192** [Spuckwaffel/UEDumper#41]
![image](https://github.com/Spuckwaffel/UEDumper/assets/9710259/9fe2f209-4f2a-4fa1-a886-42147763c026)

Game: Palworld
Engine: 5.1

**Comment by Spuckwaffel** [comment]
awesome issue! Please read the readme.md before opening an issue. You have to update the offsets to the offsets for your game.

**Comment by Chaos192** [comment]
> awesome issue! Please read the readme.md before opening an issue. You have to update the offsets to the offsets for your game.

I did...

I can dump it using any other generator but not this one. I wanted to see what about yours would make it better/worse than the others but it's not working.

`offsets.push_back({ OFFSET_SIG_DIR | OFFSET_DS, "OFFSET_GNAMES", 0, "\x48\x8D\x05\x00\x00\xEB\x13\x48\x8D\x0D\x00\x00\xE8\x00\x00\xC6\x05\x00\x00\x0F\x10", "xxx??xxxxx??x??xx???xx"});
	offsets.push_back({ OFFSET_ADDRESS | OFFSET_DS, "OFFSET_GOBJECTS", 0x0879E000 });
	offsets.push_back({ OFFSET_SIG_DIR | OFFSET_DS | OFFSET_LIVE_EDITOR, "OFFSET_UWORLD", 0, "\x48\x8B\x1D\x00\x00\x00\x00\x48\x85\xDB\x74\x33\x41\xB0", "xxx????xxxxxxx"});`

**Comment by Spuckwaffel** [comment]
toggle case preserving names and see if it works.

**Comment by Chaos192** [comment]
> preserving

https://gyazo.com/0f7ef7aaed49057b25ac489295bac2f2

now it works a little then crashes, it's weird cause I know the sig is right and even when I put the address in it still does this.

**Comment by Chaos192** [comment]
Any ideas? RE-UE4SS AND Dumper-7 both work for this game. For giggles I tried Borderlands 3 and Tiny Tina Wonderlands as well which use UE4 4.20 and neither of them work either. It's the same issue as here. I know my sigs are correct as those other dumpers are working.

**Comment by Spuckwaffel** [comment]
Yeah please start the process in visual studio to actually see where it crashes and check the output. I can't help you when i see a gif of the program crashing. 
Debugging is key
