### ISSUE TITLE
Consider using "enum class" instead of "enum" to prevent naming conflicts

### ISSUE THREAD

**Issue by awdghftyu** [Spuckwaffel/UEDumper#42]
Example problem:

`1>C:\xxx\MDK\MDK\Engine.h(43320,2): error C2365: 'COND_Max': redefinition; previous definition was 'enumerator'`
`1>(compiling source file 'main.cpp')`
`1>C:\xxx\MDK\MDK\CoreUObject.h(2326,2):`
`1>see declaration of 'COND_Max'`

CoreUObject.h
`/// Enum /Script/CoreUObject.ELifetimeCondition`
`/// Size: 0x18`
`enum ELifetimeCondition : uint8_t`
`{`
`       ...`
`	COND_NetGroup = 16,`
`	COND_Max = 17`
`};`

Engine.h
`/// Enum /Script/Engine.EDataDrivenShaderPlatformInfoCondition`
`/// Size: 0x03`
`enum EDataDrivenShaderPlatformInfoCondition : uint8_t`
`{`
`	COND_True = 0,`
`	COND_False = 1,`
`	COND_Max = 2`
`};`

Using `enum class EDataDrivenShaderPlatformInfoCondition : uint8_t` avoids naming conflicts by encapsulation and the project compiles without the need to rename. If later needed by the programmer, the numeric value can be obtained with a static cast, and the scope resolution omitted with the "using" keyword:

`using enum EDataDrivenShaderPlatformInfoCondition;`
`uint8_t a = static_cast<uint8_t>(COND_Max);`

Perhaps could be added to https://github.com/Spuckwaffel/UEDumper/blob/master/UEDumper/Engine/Generation/MDK.cpp#L233 ?

**Comment by Spuckwaffel** [comment]
hey there, thanks for the issue! This issue has been resolved in the latest version when generating the SDK but it somehow slipped through the MDK file. I will fix this in the next update. And yes, this line is perfect for the fix. Thanks!

**Comment by Spuckwaffel** [comment]
I'm not home yet and therefore cannot work on the project until further notice, however you can open a pull request to the dev branch and I will merge it into the master branch and update the release, and you'll get marked as a contributor
