### ISSUE TITLE
Size discrepancy for FUObjectItem

### ISSUE THREAD

**Issue by alemariusnexus** [Spuckwaffel/UEDumper#47]
I tried using this tool to dump the FPSDemo project that I compiled myself from UE 4.27.2.0 and kept getting stuck at package generation. I just found out why. It's about the size of [FUObjectItem](https://github.com/EpicGames/UnrealEngine/blob/3abfe77d0b24a6d8bacebd27766912e5a5fa6f02/Engine/Source/Runtime/CoreUObject/Public/UObject/UObjectArray.h#L26). In multiple places in the code (e.g. [here](https://github.com/Spuckwaffel/UEDumper/blob/fad3c65d36dc871258c159d6eddce9579003cda8/UEDumper/Engine/Core/ObjectsManager.cpp#L43) and [here](https://github.com/Spuckwaffel/UEDumper/blob/fad3c65d36dc871258c159d6eddce9579003cda8/UEDumper/Engine/Core/ObjectsManager.cpp#L169)), that struct is assumed to be 24 bytes long. In my compiled version, it is however 32 bytes long. I confirmed this by printing sizeof(FUObjectItem) in the game itself. When I change the 24 to 32 everywhere in UEDumper, the game dumps fine.

I'm not sure what causes the size discrepancy (I'm using all default options for building the UE game), but maybe it's worth making this configurable, e.g. through an additional option in UEdefinitions.h?

**Comment by Spuckwaffel** [comment]
hey there, this has been fixed in the latest development version by a kind pull request. The reason are special ue settings developers chose that changed this size. This is a rare occurrence which i only discovered once.
