### ISSUE TITLE
Duping error

### ISSUE THREAD

**Issue by zer0gra** [Spuckwaffel/UEDumper#48]
![image](https://github.com/Spuckwaffel/UEDumper/assets/140010217/bca5bfd7-0a93-4603-a2f3-944703f4aa70)
idk if some1 could help me

**Comment by SleekZ** [comment]
The error tells you what is wrong. Your GOBJECTS offset is incorrect.

**Comment by zer0gra** [comment]
> The error tells you what is wrong. Your GOBJECTS offset is incorrect.

this is a dump from fortnite so idk how to fix that

**Comment by Spuckwaffel** [comment]
what?

**Comment by zer0gra** [comment]
> what?

im trying to dump the fortnite offsets

**Comment by Spuckwaffel** [comment]
you need to have engine offsets for the dumper so the dumper can dump the games' offsets.
