### ISSUE TITLE
Cannot Click

### ISSUE THREAD

**Issue by Valen-H** [Spuckwaffel/UEDumper#6]
![image](https://github.com/Spuckwaffel/UEDumper/assets/20339324/a5bee33b-01e1-4b2c-9865-1f9275a3239e)

The Dump button is behind the gigantic log console and cannot be clicked.

**Comment by Spuckwaffel** [comment]
This is most likely the issue if you don't have the dumper window maximized (min 1920x1080). However thanks for reporting this issue, i will allow log window resizing in the future for smaller window dimensions

**Comment by Spuckwaffel** [comment]
however for a temporary fix change in file
https://github.com/Spuckwaffel/UEDumper/blob/master/UEDumper/Frontend/Windows/LogWindow.cpp

in the function windows::LogWindow::render
at ImGui::SetCursorPosY(ImGui::GetWindowSize().y - 310);
the number 310 with anything smaller (like 200) to make the log window smaller.
Keep in mind that i currently don’t know which impact it will have on the layout of other windows

**Comment by Spuckwaffel** [comment]
This will be fixed once the development branch is pushed into the main branch. The development branch has this feature now in testing mode.

**Comment by Spuckwaffel** [comment]
#9 fixed this issue
