### ISSUE TITLE
Dump game error

### ISSUE THREAD

**Issue by Cyk-Fad** [Spuckwaffel/UEDumper#7]
UE5 Game: Darker and daker.
Dumping: has chunk but all classes not found.After dump,i got nothing

**Comment by Spuckwaffel** [comment]
Hey there, this most likely indicates a wrong gnames offset where it can't find the class struct. You can check this by going into debug mode and setting a breakpoint at the start (or first if statement) of the FnameToString function in Core.cpp. Just continue the first few breakpoint his and in the fnamecache unordered map check if the entries contain valid strings. If the strings are valid check the console output for further information and send the log output here. For further help you can also ask in the discord.
