### ISSUE TITLE
Live editor wait loop

### ISSUE THREAD

**Issue by kenn1ld** [Spuckwaffel/UEDumper#75]
I keep getting a wait loop when trying out the live editor in Abiotic Factor. Look at the video below.

https://github.com/user-attachments/assets/f90a72e6-415d-4132-8971-17bc741a2e1b

**Comment by Spuckwaffel** [comment]
Hey there, are you in some special environment that is not the lobby? 
The endless wait loop most likely means that the world pointer itself changes all the time, which requires the live editor reload all its data.

**Comment by kenn1ld** [comment]
Yes, I've noticed that the Abiotic Factor GetWorld() are constantly null when debugging it. It's only valid for like 1 or 2 frames in random intervals. Do you know why?

**Comment by kenn1ld** [comment]
> Hey there, are you in some special environment that is not the lobby? The endless wait loop most likely means that the world pointer itself changes all the time, which requires the live editor reload all its data.

So, this has been solved. Fischsalat helped me solving it. For some reason, in Remnant 2 and Abiotic Factor, this code will not work correctly to fetch the world:

`
class UWorld* UWorld::GetWorld()
{
    if constexpr (Offsets::GWorld != 0)
        return *reinterpret_cast<UWorld**>(InSDKUtils::GetImageBase() + Offsets::GWorld);

    if (UEngine* Engine = UEngine::GetEngine())
    {
        if (!Engine->GameViewport)
            return nullptr;

        return Engine->GameViewport->World;
    }

    return nullptr;
}
`

It has to be changed to:

`
class UWorld* UWorld::GetWorld()
{
    if (UEngine* Engine = UEngine::GetEngine())
    {
        if (!Engine->GameViewport)
            return nullptr;

        return Engine->GameViewport->World;
    }

    return nullptr;
}
`

**Comment by kenn1ld** [comment]
> Hey there, are you in some special environment that is not the lobby? The endless wait loop most likely means that the world pointer itself changes all the time, which requires the live editor reload all its data.

So, this has been solved. Fischsalat helped me solving it. For some reason, in Remnant 2 and Abiotic Factor, this code will not work correctly to fetch the world:

```cpp
class UWorld* UWorld::GetWorld()
{
    if constexpr (Offsets::GWorld != 0)
        return *reinterpret_cast<UWorld**>(InSDKUtils::GetImageBase() + Offsets::GWorld);

    if (UEngine* Engine = UEngine::GetEngine())
    {
        if (!Engine->GameViewport)
            return nullptr;

        return Engine->GameViewport->World;
    }

    return nullptr;
}
```

It has to be changed to:

```cpp
class UWorld* UWorld::GetWorld()
{
    if (UEngine* Engine = UEngine::GetEngine())
    {
        if (!Engine->GameViewport)
            return nullptr;

        return Engine->GameViewport->World;
    }

    return nullptr;
}
```

It's solved

**Comment by Spuckwaffel** [comment]
Awesome, ill mark this as resolved.
