### ISSUE TITLE
Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works

### ISSUE THREAD

**Issue by leekinger** [Spuckwaffel/UEDumper#76]
Game:DeathlyStillnessGame
The transfer reaches 100% and fails, reporting an error

ssertion failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!"
![error](https://github.com/user-attachments/assets/866a01d1-7110-47bb-b3ba-73f64e05489a)

**Comment by Spuckwaffel** [comment]
Hey there, 
I see what the issue is, looks like the game has a couple of packages or classes with special characters, resulting the name to be empty. I will look into this!

**Comment by Spuckwaffel** [comment]
Hey there, could you launch the program and show me the stack trace and maybe where the crash appears? (Just in the stack trace to the last actual code within the dumper, NOT in some external file)

**Comment by leekinger** [comment]
I may know the reason for the error file. Some class names are in Chinese. You can try to support Chinese.
[Uploading SDK contains Chinese characters.zip…]()
