### ISSUE TITLE
MDK/SDK: Error while dumping

### ISSUE THREAD

**Issue by chadlrnsn** [Spuckwaffel/UEDumper#77]
![image](https://github.com/user-attachments/assets/f605d6cd-9d9e-407b-a026-6251d51bbacc)

This happens with any dump other than dumpspace.
Below are my definitions
```cpp
//set your games ue version
#define UE_VERSION UE_4_26


/* SDK and MDK generation */
//if this is set to true, the SDK will contain static asserts to check whether the struct sizes and members actually match their offsets
//default TRUE
#define WRITE_STATIC_ASSERT_TESTS TRUE


/* FName settings */


//in case the FNames are encrypted, it will use your decryption function in FName_decryption.h
#define USE_FNAME_ENCRYPTION FALSE

//set this to TRUE if your game uses WITH_CASE_PRESERVING_NAME (WITH_EDITORONLY_DATA)
//if GNames fail, try setting this to true
//default FALSE
#define WITH_CASE_PRESERVING_NAME TRUE

//set this to false if your generation always stops and says you have a invalid fname offset
//however all this does is check if the first item is /Scrupt/Core.UObject which should always be the case
//default TRUE
#define BREAK_IF_INVALID_NAME TRUE

```
I didn't change the rest, except offsets of course, all offsets are correct, SDK through Dumper-7 got normal, I wanted to try MDK

Game: `Wuthering Waves` V1.1
Engine ver: `4.26`

**Comment by Spuckwaffel** [comment]
Hey there, could you show me the stack trace where this happened? Press "retry" to debug the application and show me the stack trace window (mostly bottom right)

**Comment by chadlrnsn** [comment]
...
[08:48:28 - MDK GEN]: Baking package MediaAssets
[08:48:28 - MDK GEN]: Baking package LevelSequence
[08:48:28 - MDK GEN]: Baking package KuroAnim

(process 17660) terminated with code -2147483645.

It manages to generate a little bit of files.  
I'd better upload all the [logs.log](https://github.com/user-attachments/files/16277392/logs.log)

**Comment by Spuckwaffel** [comment]
Can you launch the program via Visual Studio debug mode and show me where exactly it crashes and why? I have a feeling its some function or member being extraordinarily big...

**Comment by chadlrnsn** [comment]
```
Thread 15236 terminated with code 0 (0x0).
Debug Assertion Failed!

Program: F:\source\reposition\UEDumper\x64\Debug\UEDumper.exe
File: minkernel\crts\ucrt\src\appcrt\stdio\output.cpp
Line: 282

Expression: (“Buffer too small”, 0)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
“UEDumper.exe” (Win32). Loaded “C:Windows\System32\TextShaping.dll”. Character loading is disabled by the enable and exclude parameter.
Breakpoint instruction (__debugbreak() operator or similar call) is executed in UEDumper.exe.
```
I can send video where shown all call stack

**Comment by Spuckwaffel** [comment]
sure, do that

**Comment by chadlrnsn** [comment]
https://youtu.be/itCQODqPUAI

**Comment by Spuckwaffel** [comment]
this issue will be fixed in the next release. Thanks!
