### ISSUE TITLE
Failed to Get Base Address Fortnite Branch

### ISSUE THREAD

**Issue by Thekidiacs** [Spuckwaffel/UEDumper#79]
For some reason, when I try to use the Fortnite branch when I create a project then enter the PID in decimal or hex of the win shipping of the game it says failed to get base address? The same issue occurs if I specify the win shipping name itself.

**Comment by Loscope** [comment]
happens the same to me

**Comment by Spuckwaffel** [comment]
The game uses an anticheat. The default memory reading implementation in driver.h will not work for anticheat protected games. Please add a proper solution by yourself. I will not add any support for that as that's not the goal of this dumper.
