### ISSUE TITLE
Fixed!

### ISSUE THREAD

**Issue by SaSukiTB** [Spuckwaffel/UEDumper#81]
You did a great job making this UEDumper external. I hope you can make it compatible with DMA in the future.

**Comment by Spuckwaffel** [comment]
the DMA branch exists.

**Comment by SaSukiTB** [comment]
Sorry, I didn't see it. I want to ask you what I'm doing wrong here. My DMA works fine on games, but when I run UEDumper as an administrator, I get 'Failed to initialize VMM.

```
DEVICE: FPGA: ScreamerM2 PCIe gen2 x1 [300,25,500] [v4.14,0400] [ASYNC,NORM]
[CORE]     Failed to load initial memory map from: 'mmap.txt'.

[CORE]     SHUTDOWN COMPLETED (000002287C797040).
[CORE]       TIME: 2024-10-18 11:33:18 UTC.
[CORE]       RUNTIME: 0s.

Failed to initialize VMM
```

**Comment by Spuckwaffel** [comment]
the error is right there.

**Comment by SaSukiTB** [comment]
> the error is right there.

I'm not sure I understand what you mean. Could you please clarify what you're referring to or point out where exactly the error might be?

**Comment by Spuckwaffel** [comment]
"Failed to load initial memory map from: 'mmap.txt'."

**Comment by SaSukiTB** [comment]
> Owner

Nvm i will try to fix it thx for your time
