### ISSUE TITLE
Could not find the requested Pointer Unreal Engine 5.3.2

### ISSUE THREAD

**Issue by Elior2739** [Spuckwaffel/UEDumper#84]
Hi,

I'm really new for all of this stuff but I double checked everything, And got this error:
![image](https://github.com/user-attachments/assets/2b05d5b5-a9e7-4acf-a27e-9534d8f550cf)

Offsets:
GWorld - 0x7343198
GName - 0x712FF00
GObjects - 0x71D62B0

Game Link: https://store.steampowered.com/app/2916430/Fast_Food_Simulator/
(I downloaded it using online fix)

**Comment by Elior2739** [comment]
I tried to set `USTRUCT_FAST_ISCHILDOF_IMPL` to FALSE.
But there are many errors. The logs:
[logs.txt](https://github.com/user-attachments/files/18219632/logs.txt)

**Comment by Spuckwaffel** [comment]
your first result looks better. Did the dumper stop after that error or what happened?

**Comment by Elior2739** [comment]
> your first result looks better. Did the dumper stop after that error or what happened? 

The dumper just got closed/crashed. Really don't know which of them

**Comment by Spuckwaffel** [comment]
you could try starting it in visual studio to get outputs where it crashed

**Comment by Elior2739** [comment]
Ok, I really don't know what tf happened but it now works. Thank you and sorry for wasting your time

**Comment by Spuckwaffel** [comment]
no worries, sometimes it's different per game start
